flutter_application_id:
  android: 
    id: "com.mha.lms"
    name: "MHA"
  ios:
    id: "com.mha.lms"
    name: "MHA"


flutter_icons:
  android: "ic_launchers_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 4